export const LOCAL_KEY_FAVORITES = 'LOCAL_KEY_FAVORITES' as const
export const SESSION_KEY_SEARCH_DATA_DEFAULT = 'SESSION_KEY_SEARCH_DATA_DEFAULT' as const
export const SESSION_KEY_SEARCH_DATA_FAVORITES = 'SESSION_KEY_SEARCH_DATA_FAVORITES' as const
export const SESSION_KEY_CACHE = 'SESSION_KEY_CACHE' as const
